#!/usr/bin/env python3

import sys

from zdict.models import Record

if len(sys.argv) >= 2:
    prefix = sys.argv[1]
else:
    prefix = ''

for record in Record.select().where(Record.word.startswith(prefix)):
    print(record.word)
