#!/usr/bin/env python3

import sys

from zdict.models import Record

if len(sys.argv) == 1:
    prefix = ''
elif len(sys.argv) == 2:
    prefix = sys.argv[1]
else:
    print('Usage: {} prefix'.format(sys.argv[0]), file=sys.stderr)
    exit(64)

for record in Record.select().where(Record.word.startswith(prefix)):
    print(record.word)
