#!/usr/bin/env python3

"""
This script is for developers running immediately after modifying zdict source,
in order to check if zdict works before push to github and running tests by Travis.
Just simply use `python3 ./scripts/zdict` or `.scripts/zdict`
"""

import os
import sys

from zdict import zdict
zdict.main()
